/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

/**
 * @author flamer
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrains = new javax.swing.JTable();
        btnBook = new javax.swing.JButton();
        txtTrainId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLoad.setText("Load Trains");
        btnLoad.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnLoadActionPerformed(evt);
                    }
                });

        tblTrains.setModel(
                new javax.swing.table.DefaultTableModel(
                        new Object[][] {
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null},
                            {null, null, null, null}
                        },
                        new String[] {"Title 1", "Title 2", "Title 3", "Title 4"}));
        jScrollPane1.setViewportView(tblTrains);

        btnBook.setText("Book");
        btnBook.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnBookActionPerformed(evt);
                    }
                });

        txtTrainId.setText("TR100");
        txtTrainId.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtTrainIdActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .LEADING)
                                                        .addComponent(
                                                                jScrollPane1,
                                                                javax.swing.GroupLayout
                                                                        .DEFAULT_SIZE,
                                                                940,
                                                                Short.MAX_VALUE)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addGap(
                                                                                0,
                                                                                0,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btnLoad))
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addComponent(
                                                                                txtTrainId,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE,
                                                                                167,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing
                                                                                        .LayoutStyle
                                                                                        .ComponentPlacement
                                                                                        .RELATED,
                                                                                javax.swing
                                                                                        .GroupLayout
                                                                                        .DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btnBook)))
                                        .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btnLoad)
                                        .addGap(18, 18, 18)
                                        .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                275,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .BASELINE)
                                                        .addComponent(btnBook)
                                                        .addComponent(
                                                                txtTrainId,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE,
                                                                javax.swing.GroupLayout
                                                                        .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                        .PREFERRED_SIZE))
                                        .addContainerGap(34, Short.MAX_VALUE)));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnLoadActionPerformed
        try {
            // 1. Fetch XML from Server
            String url = "http://localhost:8080/ReservationTrains/webapi/trains";
            java.net.HttpURLConnection conn =
                    (java.net.HttpURLConnection) new java.net.URL(url).openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/xml");

            java.io.BufferedReader br =
                    new java.io.BufferedReader(
                            new java.io.InputStreamReader(conn.getInputStream()));
            String line;
            StringBuilder sb = new StringBuilder();
            while ((line = br.readLine()) != null) {
                sb.append(line);
            }
            conn.disconnect();

            // 2. Simple Parsing (Extracting data manually to avoid complex JAXB setup)
            String xml = sb.toString();
            // Clear table
            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) tblTrains.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new String[] {"ID", "Depart", "Arrivee", "Heure"});

            // Very basic XML parsing logic for the demo
            String[] trains = xml.split("<train>");
            for (String t : trains) {
                if (t.contains("</train>")) {
                    String id = t.substring(t.indexOf("<id>") + 4, t.indexOf("</id>"));
                    String dep =
                            t.substring(
                                    t.indexOf("<villeDepart>") + 13, t.indexOf("</villeDepart>"));
                    String arr =
                            t.substring(
                                    t.indexOf("<villeArrivee>") + 14, t.indexOf("</villeArrivee>"));
                    String hr =
                            t.substring(
                                    t.indexOf("<heureDepart>") + 13, t.indexOf("</heureDepart>"));
                    model.addRow(new Object[] {id, dep, arr, hr});
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(
                    this, "Error loading trains: " + e.getMessage());
        }
    }

    private void btnBookActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnBookActionPerformed
        try {
            String trainId = txtTrainId.getText();
            String xmlBooking =
                    "<bookTrain>"
                            + "<numReservation>"
                            + System.currentTimeMillis()
                            + "</numReservation>"
                            + "<numTrain>"
                            + trainId
                            + "</numTrain>"
                            + "<numberPlaces>1</numberPlaces>"
                            + "</bookTrain>";

            String url = "http://localhost:8080/ReservationTrains/webapi/bookings";
            java.net.HttpURLConnection conn =
                    (java.net.HttpURLConnection) new java.net.URL(url).openConnection();
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/xml");
            conn.setDoOutput(true);

            java.io.OutputStream os = conn.getOutputStream();
            os.write(xmlBooking.getBytes());
            os.flush();

            if (conn.getResponseCode() == 204 || conn.getResponseCode() == 200) {
                javax.swing.JOptionPane.showMessageDialog(
                        this, "Booking Successful for " + trainId);
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        this, "Failed: " + conn.getResponseCode());
            }
            conn.disconnect();

        } catch (Exception e) {
            e.printStackTrace();
        }
    } // GEN-LAST:event_btnBookActionPerformed

    private void txtTrainIdActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_txtTrainIdActionPerformed
        // TODO add your handling code here:
    } // GEN-LAST:event_txtTrainIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
                    public void run() {
                        new MainFrame().setVisible(true);
                    }
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnLoad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrains;
    private javax.swing.JTextField txtTrainId;
    // End of variables declaration//GEN-END:variables
}
